title:            Syamantak Mukhopadhyay
tagline:          A beautiful theme.
description:      Describe your website.
#Comment out url when working locally to resolve base urls correctly
#url: http://syamantm.github.io

# Owner/author information
owner:
  name:           Syamantak Mukhopadhyay
  avatar:         avatar.png
  bio:            "Software Developer"
  email:          syamantak.mukhopadhyay+info@gmail.com
  twitter:        syamantm        
  github:         syamantm           
  linkedin:       syamantakmukhopadhyay
  disqus:         balzac
  location:       "London, UK"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about
  - title: Github
    url: https://github.com/syamantm
    external: true
  - title: Linkedin
    url: https://www.linkedin.com/in/syamantakmukhopadhyay
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
pygments:    true
markdown:    kramdown

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
